# Generated by Django 6.0.7 on 2026-09-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("designing", "Designing"),
                    ("printing", "Printing"),
                    ("ready", "Ready"),
                    ("delivered", "Delivered"),
                ],
                max_length=10,
            ),
        ),
    ]
