# Generated by Django 6.0.7 on 2026-09-23 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_alter_customer_options_alter_customer_address_and_more"),
        ("orders", "0002_alter_order_status"),
        ("owners", "0002_alter_owner_mobile_no_alter_owner_name_and_more"),
        ("products", "0002_alter_product_options_product_cost_price_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="order",
            name="due_date",
            field=models.DateField(
                blank=True, help_text="Target completion or delivery date", null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Custom print notes / instructions", null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="advance",
            field=models.PositiveIntegerField(
                default=0, help_text="Advance payment received in ₹"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="name",
            field=models.CharField(
                help_text="Job title or order description", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="owners.owner",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("designing", "Designing"),
                    ("printing", "Printing"),
                    ("ready", "Ready"),
                    ("delivered", "Delivered"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
