# Generated by Django 6.0.7 on 2026-09-23 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owners", "0002_alter_owner_mobile_no_alter_owner_name_and_more"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="product",
            name="cost_price",
            field=models.PositiveIntegerField(
                default=0, help_text="Cost/production price per unit in ₹"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="owners.owner",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.PositiveIntegerField(help_text="Selling price per unit in ₹"),
        ),
        migrations.AlterField(
            model_name="product",
            name="stocks",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
